name: ar_flutter_plugin_example
description: Demonstrates how to use the ar_flutter_plugin plugin.
version: 1.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Firebase dependencies to shared and manage cloud anchor IDs and related content

  firebase_core: "^1.6.0"
  cloud_firestore: "^2.5.3"
  geoflutterfire: "^3.0.1"
  path_provider: ^2.0.3
  flutter_archive: ^4.0.1
  ar_flutter_plugin: ^0.6.2
  flutter_image_compress: ^1.1.0
  share_plus: ^3.1.0
  http: ^0.13.4
  arcore_flutter_plugin:
    git:
      url: git@github.com:PaulAboulinc/arcore_flutter_plugin.git
      ref: null-safety
  another_flushbar: ^1.10.28
  restart_app: ^1.1.0
  native_screenshot: ^1.0.0
  permission_handler: ^8.3.0
  checkbox_formfield: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/models/
    - assets/models/Dinosaur/
    - assets/models/Rhinoceros/
    - assets/models/Monkey/
    - assets/models/Snake/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
